name: my_app 
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter

  
  provider: ^6.1.0
  
 
  http: ^1.1.0
  
 
  file_picker:
  
 
  camera: ^0.10.5
  
 
  image_picker: ^1.0.4
  
 
  cached_network_image: ^3.3.0
  

  path: ^1.8.3
  
  
  path_provider: ^2.1.1
  
  dio:

  shared_preferences:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
assets:
    - assets/images/
    - assets/data/

flutter:
  uses-material-design: true